<center><img src="https://github.com/DACSS-CSSmeths/guidelines/blob/main/pics/small_logo_ccs_meths.jpg?raw=true" width="700"></center>

## Geo Merging

Remember we have these maps:

In [1]:
import geopandas as gpd

mainLink='https://github.com/DACSS-CSSmeths/Spatial-Exploring/raw/refs/heads/main/'
mapsLink=mainLink+'worldMaps_Py.gpkg'

gpd.list_layers(mapsLink)

             name    geometry_type
0  countries_poly     MultiPolygon
1     rivers_line  MultiLineString
2    cities_point            Point

Let's see what the polygons have:

In [2]:
world=gpd.read_file(mapsLink, layer='countries_poly')
world.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   COUNTRY   252 non-null    object
 1   geometry  252 non-null    geometry
dtypes: geometry(1), object(1)
memory usage: 4.1+ KB

This map has no interesting information beyond the geometry, which, as we know, serves to plot the polygons.

This sections is about adding columns to the geodataframe, so that we can do more than plotting the polygons. 

Let me bring some data on countries fragility from this [study](https://fragilestatesindex.org/indicators/). I have saved the data in the GitHub repo of this session, too. Let's see those indicators per country for 2023:

In [28]:
import pandas as pd


fragilityLink=mainLink+'dataFragility/fragility2023.csv'

fragility=pd.read_csv(fragilityLink)

fragility.head()

,Country,Year,Total,C1_SecurityApparatus,C2_FactionalizedElites,C3_GroupGrievance,E1_Economy,E2_EconomicInequality,E3_HumanFlightandBrainDrain,P1_StateLegitimacy,P2_PublicServices,P3_HumanRights,S1_DemographicPressures,S2_RefugeesandIDPs,X1_ExternalIntervention,iso2,iso3
0,SOMALIA,2023,111.9,9.5,10.0,8.7,9.5,9.1,8.6,9.6,9.8,9.0,10.0,9.0,9.1,SO,SOM
1,CONGO DEMOCRATIC REPUBLIC,2023,107.2,8.8,9.6,9.4,8.1,8.4,6.4,9.3,9.3,9.3,9.7,9.8,9.1,CD,COD
2,SUDAN,2023,106.2,8.3,9.6,9.3,9.3,8.5,7.5,9.4,8.6,9.2,8.8,9.6,8.1,SD,SDN
3,SOUTH SUDAN,2023,108.5,9.9,9.2,8.6,8.6,8.6,6.5,9.8,9.7,8.7,9.7,10.0,9.2,SS,SSD
4,CHAD,2023,104.6,8.7,9.5,8.1,8.4,8.7,7.7,9.1,9.6,8.4,9.5,9.0,7.9,TD,TCD

As you see, you have several variables:

In [4]:
fragility.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      179 non-null    object
 1   Year                         179 non-null    int64
 2   Total                        179 non-null    float64
 3   C1_SecurityApparatus         179 non-null    float64
 4   C2_FactionalizedElites       179 non-null    float64
 5   C3_GroupGrievance            179 non-null    float64
 6   E1_Economy                   179 non-null    float64
 7   E2_EconomicInequality        179 non-null    float64
 8   E3_HumanFlightandBrainDrain  179 non-null    float64
 9   P1_StateLegitimacy           179 non-null    float64
 10  P2_PublicServices            179 non-null    float64
 11  P3_HumanRights               179 non-null    float64
 12  S1_DemographicPressures      179 non-null    float64
 13  S2_RefugeesandIDPs           179 non-null    float64
 14  X1_ExternalIntervention      179 non-null    float64
 15  iso2                         178 non-null    object
 16  iso3                         179 non-null    object
dtypes: float64(13), int64(1), object(3)
memory usage: 23.9+ KB

These indicators are explained [here](https://fragilestatesindex.org/indicators/); and at the end, you have the ISO codes for the countries.

# Basic merging

For the merging process, we need a common column. The country name is the option.

In [5]:
world.head()

               COUNTRY                                           geometry
0  Aruba (Netherlands)  MULTIPOLYGON (((-69.88223 12.41111, -69.94695 ...
1  Antigua and Barbuda  MULTIPOLYGON (((-61.73889 17.54055, -61.75195 ...
2          Afghanistan  MULTIPOLYGON (((61.27656 35.60725, 61.29638 35...
3              Algeria  MULTIPOLYGON (((-5.15213 30.18047, -5.13917 30...
4           Azerbaijan  MULTIPOLYGON (((46.54037 38.87559, 46.49554 38...

The map has the country in lower case, while the fragility data has the countries in upper case; then:

In [6]:
# to upper case.
world['COUNTRY']=world['COUNTRY'].str.upper()

When you add data to the map, you have to follow this order:

In [7]:
world.merge(fragility, left_on='COUNTRY', right_on='Country')

,COUNTRY,geometry,Country,Year,Total,C1_SecurityApparatus,C2_FactionalizedElites,C3_GroupGrievance,E1_Economy,E2_EconomicInequality,E3_HumanFlightandBrainDrain,P1_StateLegitimacy,P2_PublicServices,P3_HumanRights,S1_DemographicPressures,S2_RefugeesandIDPs,X1_ExternalIntervention,iso2,iso3
0,ANTIGUA AND BARBUDA,"MULTIPOLYGON (((-61.73889 17.54055, -61.75195 ...",ANTIGUA AND BARBUDA,2023,53.8,4.9,3.7,3.6,6.6,5.1,6.2,3.6,3.8,3.8,3.7,2.7,6.1,AG,ATG
1,AFGHANISTAN,"MULTIPOLYGON (((61.27656 35.60725, 61.29638 35...",AFGHANISTAN,2023,106.6,9.7,8.7,8.3,9.6,8.2,8.5,9.4,10.0,8.7,9.2,8.6,7.7,AF,AFG
2,ALGERIA,"MULTIPOLYGON (((-5.15213 30.18047, -5.13917 30...",ALGERIA,2023,70.0,5.8,6.9,7.0,6.2,5.2,5.1,7.6,5.0,6.9,5.0,6.2,3.1,DZ,DZA
3,AZERBAIJAN,"MULTIPOLYGON (((46.54037 38.87559, 46.49554 38...",AZERBAIJAN,2023,72.7,5.8,7.9,5.9,4.5,4.5,4.6,9.2,4.9,7.5,3.8,6.3,7.8,AZ,AZE
4,ALBANIA,"MULTIPOLYGON (((20.79192 40.43154, 20.78722 40...",ALBANIA,2023,56.8,4.8,6.2,3.5,6.1,2.9,8.5,5.0,3.8,3.6,4.1,2.8,5.5,AL,ALB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,YEMEN,"MULTIPOLYGON (((48.68639 14.0375, 48.61 14.044...",YEMEN,2023,108.9,8.6,9.9,8.8,9.9,7.9,6.4,9.8,9.6,9.6,9.6,9.6,9.2,YE,YEM
164,ZAMBIA,"MULTIPOLYGON (((30.21302 -14.98172, 30.21917 -...",ZAMBIA,2023,81.8,3.9,5.6,5.9,8.2,9.1,6.3,6.7,8.1,7.5,9.4,4.9,6.2,ZM,ZMB
165,ZIMBABWE,"MULTIPOLYGON (((32.48888 -21.34445, 32.46541 -...",ZIMBABWE,2023,96.9,8.4,10.0,5.9,9.2,7.8,7.1,8.9,8.8,7.8,8.7,7.6,6.7,ZW,ZWE
166,SOUTH SUDAN,"MULTIPOLYGON (((34.21807 9.96458, 34.20722 9.9...",SOUTH SUDAN,2023,108.5,9.9,9.2,8.6,8.6,8.6,6.5,9.8,9.7,8.7,9.7,10.0,9.2,SS,SSD
167,INDONESIA,"MULTIPOLYGON (((123.21846 -10.80917, 123.19832...",INDONESIA,2023,65.6,5.2,7.1,6.9,4.1,4.4,5.7,4.7,5.9,6.5,7.0,4.4,3.7,ID,IDN

Notice that the merge produces 168 rows, and the map has originally:

In [8]:
# amount of rows in map
world.shape[0]

252

The fragility has these amount of rows:

In [9]:
fragility.shape[0]

179

Using the normal merge we may lose some rows. Let's see if we can recover some rows.

## Fuzzy merging

Let's see what is not matching:

In [29]:
onlyFragil=set(fragility.Country)- set(world.COUNTRY)
onlyMap=set(world.COUNTRY)- set(fragility.Country)

Check here:

In [30]:
onlyFragil

{'BRUNEI DARUSSALAM',
 'CONGO DEMOCRATIC REPUBLIC',
 'CONGO REPUBLIC',
 "COTE D'IVOIRE",
 'ESWATINI',
 'GUINEA BISSAU',
 'KYRGYZ REPUBLIC',
 'MICRONESIA',
 'SAMOA',
 'SLOVAK REPUBLIC',
 'TIMOR-LESTE'}

In [31]:
# and here
onlyMap

{'AMERICAN SAMOA (US)',
 'AMERICAN VIRGIN ISLANDS (US)',
 'ANDORRA',
 'ANGUILLA (UK)',
 'ANTARCTICA',
 'ARUBA (NETHERLANDS)',
 'BAKER ISLAND (US)',
 'BERMUDA (UK)',
 'BONAIRE (NETHERLANDS)',
 'BOUVET ISLAND (NORWAY)',
 'BRITISH INDIAN OCEAN TERRITORY (UK)',
 'BRITISH VIRGIN ISLANDS(UK)',
 'BRUNEI',
 'CAYMAN ISLANDS (UK)',
 'CHRISTMAS ISLAND (AUSTRALIA)',
 'COCOS (KEELING) ISLANDS (AUSTRALIA)',
 'CONGO',
 'COOK ISLANDS (NEW ZEALAND)',
 'CURACAO (NETHERLANDS)',
 'DEMOCRATIC REPUBLIC OF THE CONGO',
 'DOMINICA',
 'EAST TIMOR',
 'FALKLAND ISLANDS (UK)',
 'FAROE ISLANDS (DENMARK)',
 'FEDERATED STATES OF MICRONESIA',
 'FRENCH GUIANA (FRANCE)',
 'FRENCH POLYNESIA (FRANCE)',
 'FRENCH SOUTHERN & ANTARCTIC LANDS (FRANCE)',
 'GIBRALTAR (UK)',
 'GLORIOSO ISLANDS (FRANCE)',
 'GREENLAND (DENMARK)',
 'GUADELOUPE (FRANCE)',
 'GUAM (US)',
 'GUERNSEY (UK)',
 'GUINEA-BISSAU',
 'HEARD ISLAND & MCDONALD ISLANDS (AUSTRALIA)',
 'HOWLAND ISLAND (US)',
 'ISLE OF MAN (UK)',
 'IVORY COAST',
 'JAN MAYEN (NORWAY)',
 'JARVIS ISLAND (US)',
 'JERSEY (UK)',
 'JOHNSTON ATOLL (US)',
 'JUAN DE NOVA ISLAND (FRANCE)',
 'KIRIBATI',
 'KYRGYZSTAN',
 'LIECHTENSTEIN',
 'MARSHALL ISLANDS',
 'MARTINIQUE (FRANCE)',
 'MAYOTTE (FRANCE)',
 'MIDWAY ISLANDS (US)',
 'MONACO',
 'MONTSERRAT (UK)',
 'NAURU',
 'NEW CALEDONIA (FRANCE)',
 'NIUE (NEW ZEALAND)',
 'NORFOLK ISLAND (AUSTRALIA)',
 'NORTHERN MARIANA ISLANDS (US)',
 'PALAU (US)',
 'PARACEL ISLANDS (CHINA)',
 'PITCAIRN ISLANDS (UK)',
 'PUERTO RICO (US)',
 'REUNION (FRANCE)',
 'SAN MARINO',
 'SLOVAKIA',
 'SOUTH GEORGIA AND THE SOUTH SANDWICH IS (UK)',
 'SPRATLY ISLANDS (DISPUTED)',
 'ST. HELENA (UK)',
 'ST. KITTS AND NEVIS',
 'ST. LUCIA',
 'ST. PIERRE AND MIQUELON (FRANCE)',
 'ST. VINCENT AND THE GRENADINES',
 'SVALBARD (NORWAY)',
 'SWAZILAND',
 'TAIWAN',
 'TOKELAU (NEW ZEALAND)',
 'TONGA',
 'TURKS AND CAICOS ISLANDS (UK)',
 'TUVALU',
 'VANUATU',
 'WAKE ISLAND (US)',
 'WALLIS AND FUTUNA (FRANCE)',
 'WESTERN SAHARA',
 'WESTERN SAMOA'}

Let's find similar names:

In [32]:
from thefuzz import process

[(country, process.extractOne(country,onlyMap)) for country in sorted(onlyFragil)]

[('BRUNEI DARUSSALAM', ('BRUNEI', 90)),
 ('CONGO DEMOCRATIC REPUBLIC', ('DEMOCRATIC REPUBLIC OF THE CONGO', 95)),
 ('CONGO REPUBLIC', ('CONGO', 90)),
 ("COTE D'IVOIRE", ('IVORY COAST', 63)),
 ('ESWATINI', ('MARTINIQUE (FRANCE)', 60)),
 ('GUINEA BISSAU', ('GUINEA-BISSAU', 100)),
 ('KYRGYZ REPUBLIC', ('DEMOCRATIC REPUBLIC OF THE CONGO', 86)),
 ('MICRONESIA', ('FEDERATED STATES OF MICRONESIA', 90)),
 ('SAMOA', ('AMERICAN SAMOA (US)', 90)),
 ('SLOVAK REPUBLIC', ('DEMOCRATIC REPUBLIC OF THE CONGO', 86)),
 ('TIMOR-LESTE', ('EAST TIMOR', 81))]

Let's change the difficult ones manually:

In [33]:
changesDict={'Country':{'ESWATINI': 'SWAZILAND'}}

fragility.replace(changesDict,inplace=True)

In [36]:
onlyFragil=set(fragility.Country)- set(world.COUNTRY)
onlyMap=set(world.COUNTRY)- set(fragility.Country)
[(country, process.extractOne(country,onlyMap)) for country in sorted(onlyFragil) if country!='SAMOA']

[('BRUNEI DARUSSALAM', ('BRUNEI', 90)),
 ('CONGO DEMOCRATIC REPUBLIC', ('DEMOCRATIC REPUBLIC OF THE CONGO', 95)),
 ('CONGO REPUBLIC', ('CONGO', 90)),
 ("COTE D'IVOIRE", ('IVORY COAST', 63)),
 ('GUINEA BISSAU', ('GUINEA-BISSAU', 100)),
 ('KYRGYZ REPUBLIC', ('DEMOCRATIC REPUBLIC OF THE CONGO', 86)),
 ('MICRONESIA', ('FEDERATED STATES OF MICRONESIA', 90)),
 ('SLOVAK REPUBLIC', ('DEMOCRATIC REPUBLIC OF THE CONGO', 86)),
 ('TIMOR-LESTE', ('EAST TIMOR', 81))]

In [37]:
[(country, process.extractOne(country,onlyMap)) for country in sorted(onlyFragil) 
 if country!='SAMOA' and process.extractOne(country,onlyMap)[1]>=90]

[('BRUNEI DARUSSALAM', ('BRUNEI', 90)),
 ('CONGO DEMOCRATIC REPUBLIC', ('DEMOCRATIC REPUBLIC OF THE CONGO', 95)),
 ('CONGO REPUBLIC', ('CONGO', 90)),
 ('GUINEA BISSAU', ('GUINEA-BISSAU', 100)),
 ('MICRONESIA', ('FEDERATED STATES OF MICRONESIA', 90))]

In [38]:
# then:
try1={country: process.extractOne(country,onlyMap)[0] for country in sorted(onlyFragil) 
 if country!='SAMOA' and process.extractOne(country,onlyMap)[1]>=90}
try1

{'BRUNEI DARUSSALAM': 'BRUNEI',
 'CONGO DEMOCRATIC REPUBLIC': 'DEMOCRATIC REPUBLIC OF THE CONGO',
 'CONGO REPUBLIC': 'CONGO',
 'GUINEA BISSAU': 'GUINEA-BISSAU',
 'MICRONESIA': 'FEDERATED STATES OF MICRONESIA'}

In [39]:
changesDict1={'Country':try1}

fragility.replace(changesDict1,inplace=True)


# updating
onlyFragil=set(fragility.Country)- set(world.COUNTRY)
onlyMap=set(world.COUNTRY)- set(fragility.Country)

In [42]:
# new matches
[(country, process.extractOne(country,onlyMap)) for country in sorted(onlyFragil) if country!='SAMOA']

[("COTE D'IVOIRE", ('IVORY COAST', 63)),
 ('KYRGYZ REPUBLIC', ('KYRGYZSTAN', 68)),
 ('SLOVAK REPUBLIC', ('SLOVAKIA', 77)),
 ('TIMOR-LESTE', ('EAST TIMOR', 81))]

In [43]:
# then:
try2={country: process.extractOne(country,onlyMap)[0] for country in sorted(onlyFragil) 
 if country!='SAMOA'}
try2

{"COTE D'IVOIRE": 'IVORY COAST',
 'KYRGYZ REPUBLIC': 'KYRGYZSTAN',
 'SLOVAK REPUBLIC': 'SLOVAKIA',
 'TIMOR-LESTE': 'EAST TIMOR'}

In [44]:
changesDict2={'Country':try2}

fragility.replace(changesDict2,inplace=True)


# updating
onlyFragil=set(fragility.Country)- set(world.COUNTRY)
onlyMap=set(world.COUNTRY)- set(fragility.Country)

In [45]:
# new matches
[(country, process.extractOne(country,onlyMap)) for country in sorted(onlyFragil)]

[('SAMOA', ('WESTERN SAMOA', 90))]

In [46]:
# then:
try3={country: process.extractOne(country,onlyMap)[0] for country in sorted(onlyFragil) }
try3

{'SAMOA': 'WESTERN SAMOA'}

Making changes and updating:

In [47]:
changesDict3={'Country':try3}

fragility.replace(changesDict3,inplace=True)


# updating
onlyFragil=set(fragility.Country)- set(world.COUNTRY)
onlyMap=set(world.COUNTRY)- set(fragility.Country)

# new matches
[(country, process.extractOne(country,onlyMap)) for country in sorted(onlyFragil)]

[]

We can not improve the situation.

Now, when you merge a GDF with a DF, **the GDF has to be on the left**:

In [48]:
theMapAndData=world.merge(fragility,left_on='COUNTRY', right_on='Country')
# here it is (new map):
theMapAndData.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   COUNTRY                      179 non-null    object
 1   geometry                     179 non-null    geometry
 2   Country                      179 non-null    object
 3   Year                         179 non-null    int64
 4   Total                        179 non-null    float64
 5   C1_SecurityApparatus         179 non-null    float64
 6   C2_FactionalizedElites       179 non-null    float64
 7   C3_GroupGrievance            179 non-null    float64
 8   E1_Economy                   179 non-null    float64
 9   E2_EconomicInequality        179 non-null    float64
 10  E3_HumanFlightandBrainDrain  179 non-null    float64
 11  P1_StateLegitimacy           179 non-null    float64
 12  P2_PublicServices            179 non-null    float64
 13  P3_HumanRights               179 non-null    float64
 14  S1_DemographicPressures      179 non-null    float64
 15  S2_RefugeesandIDPs           179 non-null    float64
 16  X1_ExternalIntervention      179 non-null    float64
 17  iso2                         178 non-null    object
 18  iso3                         179 non-null    object
dtypes: float64(13), geometry(1), int64(1), object(4)
memory usage: 26.7+ KB

# Choropleths

We should plan how to color the polygons based on some variable:

In [57]:
theMapAndData.describe()

,Year,Total,C1_SecurityApparatus,C2_FactionalizedElites,C3_GroupGrievance,E1_Economy,E2_EconomicInequality,E3_HumanFlightandBrainDrain,P1_StateLegitimacy,P2_PublicServices,P3_HumanRights,S1_DemographicPressures,S2_RefugeesandIDPs,X1_ExternalIntervention
count,179.0,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000
mean,2023.0,65.832402,5.014525,6.618436,5.574860,5.687151,5.323464,5.184358,5.741341,5.459218,5.436872,5.955866,4.764246,5.072067
std,0.0,23.966251,2.379810,2.427869,2.367757,2.200741,2.068546,2.079591,2.901853,2.581299,2.602588,2.278726,2.373935,2.577801
min,2023.0,14.500000,0.300000,1.000000,0.300000,1.000000,1.400000,0.400000,0.300000,0.900000,0.400000,1.100000,0.500000,0.300000
25%,2023.0,49.000000,3.350000,4.950000,3.600000,4.100000,3.650000,3.700000,3.650000,3.450000,3.600000,4.100000,2.800000,3.150000
50%,2023.0,68.200000,5.100000,7.200000,5.500000,6.000000,5.200000,5.600000,6.400000,5.100000,5.700000,5.900000,4.500000,5.300000
75%,2023.0,82.200000,6.700000,8.550000,7.550000,7.150000,7.200000,6.600000,8.100000,7.950000,7.500000,8.050000,6.450000,7.000000
max,2023.0,111.900000,10.000000,10.000000,9.700000,9.900000,9.600000,10.000000,10.000000,10.000000,9.900000,10.000000,10.000000,10.000000

In [66]:
theMapAndData.iloc[:,5:15].boxplot()

AssertionError: 7

In [56]:
import seaborn as sea

sea.histplot(data=theMapAndData, x="C1_SecurityApparatus")

Let's see other possibilities to cut the data (instead of the amount of intervals presented in the histogram), but please install [**numba**](https://numba.readthedocs.io/en/stable/user/installing.html) before runing the next code; also make sure you have **pysal**, **mapclassify** and **numpy** installed:

In [23]:
pip show numba pysal mapclassify numpy

Name: numba
Version: 0.59.1
Summary: compiling Python code using LLVM
Home-page: https://numba.pydata.org
Author:
Author-email:
License: BSD
Location: /Users/JoseManuel/opt/anaconda3/envs/ASIES/lib/python3.11/site-packages
Requires: llvmlite, numpy
Required-by: hyppo, pynndescent, quantecon, segregation, umap-learn
---
Name: pysal
Version: 23.7
Summary: A library of spatial analysis functions.
Home-page: http://pysal.org
Author:
Author-email:
License: BSD
Location: /Users/JoseManuel/opt/anaconda3/envs/ASIES/lib/python3.11/site-packages
Requires: access, esda, giddy, inequality, libpysal, mapclassify, mgwr, momepy, pointpats, segregation, spaghetti, spglm, spint, splot, spopt, spreg, spvcm, tobler
Required-by:
---
Name: mapclassify
Version: 2.6.1
Summary: Classification Schemes for Choropleth Maps.
Home-page:
Author:
Author-email:
License: BSD 3-Clause
Location: /Users/JoseManuel/opt/anaconda3/envs/ASIES/lib/python3.11/site-packages
Requires: networkx, numpy, pandas, scikit-learn, scipy
Required-by: pysal, segregation, splot, spopt
---
Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: /Users/JoseManuel/opt/anaconda3/envs/ASIES/lib/python3.11/site-packages
Requires:
Required-by: access, ahpy, altair, autograd, BiocFrame, biocutils, contourpy, folium, GenomicRanges, gensim, geopandas, graspologic, hiveplotlib, hyppo, inequality, IRanges, libpysal, mapclassify, matplotlib, mgwr, ncls, netgraph, netwulf, numba, optuna, pandas, patsy, pointpats, POT, pyarrow, Pyfrontier, pyogrio, Python-EasyGraph, python-louvain, quantecon, rasterio, rasterstats, rds2py, scikit-learn, scipy, seaborn, segregation, shapely, snuggs, spaghetti, spglm, spint, splot, spopt, spreg, spvcm, statsmodels, tobler, umap-learn
Note: you may need to restart the kernel to use updated packages.

In [24]:
import mapclassify 
import numpy as np

np.random.seed(12345) # so we all get the same results!

# let's try 5 intervals
K=5
theVar=theMapAndData.Total
# same interval width, easy interpretation
ei5 = mapclassify.EqualInterval(theVar, k=K)
# same interval width based on standard deviation, easy - but not as the previous one, poor when high skewness
msd = mapclassify.StdMean(theVar)
# interval width varies, counts per interval are close, not easy to grasp, repeated values complicate cuts                                
q5=mapclassify.Quantiles(theVar,k=K)

# based on similarity, good for multimodal data 
mb5 = mapclassify.MaximumBreaks(theVar, k=K)
# based on similarity, good for skewed data
ht = mapclassify.HeadTailBreaks(theVar) # no K needed
# based on similarity, optimizer
fj5 = mapclassify.FisherJenks(theVar, k=K)
# based on similarity, optimizer
jc5 = mapclassify.JenksCaspall(theVar, k=K)
# based on similarity, optimizer
mp5 = mapclassify.MaxP(theVar, k=K)

How can we select the right classification?
Let me use the the Absolute deviation around class median (ADCM) to make the comparisson:

In [25]:
class5 = ei5,msd, q5,mb5,  ht, fj5, jc5, mp5
# Collect ADCM for each classifier
fits = np.array([ c.adcm for c in class5])
# Convert ADCM scores to a DataFrame
adcms = pd.DataFrame(fits)
# Add classifier names
adcms['classifier'] = [c.name for c in class5]
# Add column names to the ADCM
adcms.columns = ['ADCM', 'Classifier']

Now, plot the **adcms**:

In [26]:
adcms.sort_values('ADCM').plot.barh(x='Classifier')

Let's save the best three strategies:

In [27]:
theMapAndData.loc[:,'Total_ei5'] = ei5.yb
theMapAndData.loc[:,'Total_fj5'] = fj5.yb
theMapAndData.loc[:,'Total_jc5'] = jc5.yb

In [28]:
# there you are
theMapAndData.head()

,COUNTRY,geometry,Country,Year,Total,C1_SecurityApparatus,C2_FactionalizedElites,C3_GroupGrievance,E1_Economy,E2_EconomicInequality,...,P2_PublicServices,P3_HumanRights,S1_DemographicPressures,S2_RefugeesandIDPs,X1_ExternalIntervention,iso2,iso3,Total_ei5,Total_fj5,Total_jc5
0,ANTIGUA AND BARBUDA,"MULTIPOLYGON (((-61.73889 17.54055, -61.75195 ...",ANTIGUA AND BARBUDA,2023,53.8,4.9,3.7,3.6,6.6,5.1,...,3.8,3.8,3.7,2.7,6.1,AG,ATG,2,1,1
1,AFGHANISTAN,"MULTIPOLYGON (((61.27656 35.60725, 61.29638 35...",AFGHANISTAN,2023,106.6,9.7,8.7,8.3,9.6,8.2,...,10.0,8.7,9.2,8.6,7.7,AF,AFG,4,4,4
2,ALGERIA,"MULTIPOLYGON (((-5.15213 30.18047, -5.13917 30...",ALGERIA,2023,70.0,5.8,6.9,7.0,6.2,5.2,...,5.0,6.9,5.0,6.2,3.1,DZ,DZA,2,2,2
3,AZERBAIJAN,"MULTIPOLYGON (((46.54037 38.87559, 46.49554 38...",AZERBAIJAN,2023,72.7,5.8,7.9,5.9,4.5,4.5,...,4.9,7.5,3.8,6.3,7.8,AZ,AZE,2,2,2
4,ALBANIA,"MULTIPOLYGON (((20.79192 40.43154, 20.78722 40...",ALBANIA,2023,56.8,4.8,6.2,3.5,6.1,2.9,...,3.8,3.6,4.1,2.8,5.5,AL,ALB,2,2,1

Let's check the mean of 'Total_mnmx' by the labels of the columns created (from '0' to '4')

In [29]:
indexList=['Total_ei5','Total_fj5','Total_jc5']
aggregator={'Total': ['mean']}

pd.concat([theMapAndData[['Total',col]].groupby(col,as_index=False).agg(aggregator) for col in indexList],axis=1)

  Total_ei5       Total Total_fj5      Total Total_jc5      Total
                   mean                 mean                 mean
0         0   22.854545         0  23.356522         0  23.356522
1         1   44.793333         1  46.771429         1  47.318919
2         2   64.109804         2  65.377778         2  66.102222
3         3   82.029412         3  80.406977         3  80.555000
4         4  100.800000         4  98.287500         4  98.003030

Verify data types:

In [30]:
theMapAndData.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   COUNTRY                      178 non-null    object
 1   geometry                     178 non-null    geometry
 2   Country                      178 non-null    object
 3   Year                         178 non-null    int64
 4   Total                        178 non-null    float64
 5   C1_SecurityApparatus         178 non-null    float64
 6   C2_FactionalizedElites       178 non-null    float64
 7   C3_GroupGrievance            178 non-null    float64
 8   E1_Economy                   178 non-null    float64
 9   E2_EconomicInequality        178 non-null    float64
 10  E3_HumanFlightandBrainDrain  178 non-null    float64
 11  P1_StateLegitimacy           178 non-null    float64
 12  P2_PublicServices            178 non-null    float64
 13  P3_HumanRights               178 non-null    float64
 14  S1_DemographicPressures      178 non-null    float64
 15  S2_RefugeesandIDPs           178 non-null    float64
 16  X1_ExternalIntervention      178 non-null    float64
 17  iso2                         177 non-null    object
 18  iso3                         178 non-null    object
 19  Total_ei5                    178 non-null    int64
 20  Total_fj5                    178 non-null    int64
 21  Total_jc5                    178 non-null    int64
dtypes: float64(13), geometry(1), int64(4), object(4)
memory usage: 30.7+ KB

Let me create a copy of those columns with new names:

In [31]:
newColNames=[ name+"_cat" for name in indexList]

theMapAndData[newColNames]=theMapAndData.loc[:,indexList]
theMapAndData.head()

,COUNTRY,geometry,Country,Year,Total,C1_SecurityApparatus,C2_FactionalizedElites,C3_GroupGrievance,E1_Economy,E2_EconomicInequality,...,S2_RefugeesandIDPs,X1_ExternalIntervention,iso2,iso3,Total_ei5,Total_fj5,Total_jc5,Total_ei5_cat,Total_fj5_cat,Total_jc5_cat
0,ANTIGUA AND BARBUDA,"MULTIPOLYGON (((-61.73889 17.54055, -61.75195 ...",ANTIGUA AND BARBUDA,2023,53.8,4.9,3.7,3.6,6.6,5.1,...,2.7,6.1,AG,ATG,2,1,1,2,1,1
1,AFGHANISTAN,"MULTIPOLYGON (((61.27656 35.60725, 61.29638 35...",AFGHANISTAN,2023,106.6,9.7,8.7,8.3,9.6,8.2,...,8.6,7.7,AF,AFG,4,4,4,4,4,4
2,ALGERIA,"MULTIPOLYGON (((-5.15213 30.18047, -5.13917 30...",ALGERIA,2023,70.0,5.8,6.9,7.0,6.2,5.2,...,6.2,3.1,DZ,DZA,2,2,2,2,2,2
3,AZERBAIJAN,"MULTIPOLYGON (((46.54037 38.87559, 46.49554 38...",AZERBAIJAN,2023,72.7,5.8,7.9,5.9,4.5,4.5,...,6.3,7.8,AZ,AZE,2,2,2,2,2,2
4,ALBANIA,"MULTIPOLYGON (((20.79192 40.43154, 20.78722 40...",ALBANIA,2023,56.8,4.8,6.2,3.5,6.1,2.9,...,2.8,5.5,AL,ALB,2,2,1,2,2,1

In [32]:
# renaming
newLabelsForLevels={0:"0_Great", 1:"1_Good", 2:"2_Middle", 3:"3_Bad", 4:"4_Poor"}

theMapAndData[newColNames]=theMapAndData.loc[:,newColNames].replace(newLabelsForLevels)
theMapAndData.drop(columns=['Country'],inplace=True)
theMapAndData

,COUNTRY,geometry,Year,Total,C1_SecurityApparatus,C2_FactionalizedElites,C3_GroupGrievance,E1_Economy,E2_EconomicInequality,E3_HumanFlightandBrainDrain,...,S2_RefugeesandIDPs,X1_ExternalIntervention,iso2,iso3,Total_ei5,Total_fj5,Total_jc5,Total_ei5_cat,Total_fj5_cat,Total_jc5_cat
0,ANTIGUA AND BARBUDA,"MULTIPOLYGON (((-61.73889 17.54055, -61.75195 ...",2023,53.8,4.9,3.7,3.6,6.6,5.1,6.2,...,2.7,6.1,AG,ATG,2,1,1,2_Middle,1_Good,1_Good
1,AFGHANISTAN,"MULTIPOLYGON (((61.27656 35.60725, 61.29638 35...",2023,106.6,9.7,8.7,8.3,9.6,8.2,8.5,...,8.6,7.7,AF,AFG,4,4,4,4_Poor,4_Poor,4_Poor
2,ALGERIA,"MULTIPOLYGON (((-5.15213 30.18047, -5.13917 30...",2023,70.0,5.8,6.9,7.0,6.2,5.2,5.1,...,6.2,3.1,DZ,DZA,2,2,2,2_Middle,2_Middle,2_Middle
3,AZERBAIJAN,"MULTIPOLYGON (((46.54037 38.87559, 46.49554 38...",2023,72.7,5.8,7.9,5.9,4.5,4.5,4.6,...,6.3,7.8,AZ,AZE,2,2,2,2_Middle,2_Middle,2_Middle
4,ALBANIA,"MULTIPOLYGON (((20.79192 40.43154, 20.78722 40...",2023,56.8,4.8,6.2,3.5,6.1,2.9,8.5,...,2.8,5.5,AL,ALB,2,2,1,2_Middle,2_Middle,1_Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,ZAMBIA,"MULTIPOLYGON (((30.21302 -14.98172, 30.21917 -...",2023,81.8,3.9,5.6,5.9,8.2,9.1,6.3,...,4.9,6.2,ZM,ZMB,3,3,3,3_Bad,3_Bad,3_Bad
174,ZIMBABWE,"MULTIPOLYGON (((32.48888 -21.34445, 32.46541 -...",2023,96.9,8.4,10.0,5.9,9.2,7.8,7.1,...,7.6,6.7,ZW,ZWE,4,4,4,4_Poor,4_Poor,4_Poor
175,SOUTH SUDAN,"MULTIPOLYGON (((34.21807 9.96458, 34.20722 9.9...",2023,108.5,9.9,9.2,8.6,8.6,8.6,6.5,...,10.0,9.2,SS,SSD,4,4,4,4_Poor,4_Poor,4_Poor
176,INDONESIA,"MULTIPOLYGON (((123.21846 -10.80917, 123.19832...",2023,65.6,5.2,7.1,6.9,4.1,4.4,5.7,...,4.4,3.7,ID,IDN,2,2,2,2_Middle,2_Middle,2_Middle
177,EAST TIMOR,"MULTIPOLYGON (((124.41824 -9.3001, 124.40446 -...",2023,77.5,5.6,8.3,5.0,7.1,5.9,6.6,...,5.7,8.0,TL,TLS,3,3,3,3_Bad,3_Bad,3_Bad

We are ready for a choropleth:

In [33]:
import matplotlib.pyplot as plt

f, ax = plt.subplots(1, figsize=(10, 10))
theMapAndData.plot(column='Total_ei5', # variable to plot
                   cmap='viridis', # set of colors
                   categorical=True, # can be interpreted as category
                   edgecolor='white', # border color
                   linewidth=0., # width of border
                   alpha=1, # level of transparency (0 is invisible)
                   legend=True, # need a legend?
                   # location of legend: 'best', 'upper right', 'upper left', 'lower left',
                   # 'lower right', 'right', 'center left', 'center right',
                   # 'lower center', 'upper center', 'center'
                   legend_kwds={'loc':"lower left"}, 
        ax=ax
       )

ax.set_axis_off()

In [34]:
# alternatively:

import matplotlib.pyplot as plt

f, ax = plt.subplots(1, figsize=(10, 10))
theMapAndData.plot(column='Total_ei5_cat', # annotated
        cmap='viridis', 
        categorical=True,
        edgecolor='white', 
        linewidth=0., 
        alpha=1, 
        legend=True,
        legend_kwds={'loc':3},
        ax=ax
       )

ax.set_axis_off()

Once you know the ADCM, you can request the choropleth without creating a variable:

In [35]:
import matplotlib.pyplot as plt

f, ax = plt.subplots(1, figsize=(10, 10))
theMapAndData.plot(column='Total', 
        cmap='viridis', 
                   scheme="equal_interval",
        edgecolor='white', 
        linewidth=0., 
        alpha=0.75, 
        legend=True,
        legend_kwds={'loc':3},
        ax=ax
       )

ax.set_axis_off()

In [36]:
import matplotlib.pyplot as plt

f, ax = plt.subplots(1, figsize=(10, 10))
theMapAndData.plot(column='Total_ei5_cat', 
        cmap='viridis', 
        categorical=True,
        edgecolor='white', 
        linewidth=0., 
        alpha=0.75, 
        legend=True,
        legend_kwds={'loc':"lower right"},
        ax=ax
       )

ax.set_axis_off()

Let's save our data

In [37]:
theMapAndData.to_file(os.path.join("maps","theMapAndData.gpkg"), layer='fragility', driver="GPKG")

NameError: name 'os' is not defined

<div class="alert alert-danger">
  <strong>CHALLENGE 1</strong> 
    <br> * Create a public repo named "week2_spatial" with its README file. (1 point)
    <br> * Clone the repo to your computer. (1 point)
    <br> * In the local repo in your computer, create a folder named "data". (1 point)
    <br> * Get Three maps for the same country: the lines can be rivers, highways or similar; the points have to be airports; and the polygons  of the 2rd administrative division ('provinces' in Perú, 'counties' in USA). Download those maps into the "data" folder. You can find airports here: https://ourairports.com/data/ (5 points)
    <br> * Plot in one map the three layers of maps, including the code. (5 points)
    <br> * Publish the three layer map. (3 points)
    <br> * Update the README to offer a quick explanation, the data dictionary, and the link to the published map. (2 points)
    <br> * Make sure the code is well organized (explanations, comments, no warnings, no python messages). (2 points)
    
</div>

<div class="alert alert-danger">
  <strong>CHALLENGE 2</strong> 
    <br> * Create a public repo named week2_spatial with its README file. (1 point)
    <br> * Clone the repo to your computer. (1 point)
    <br> * In the local repo in your computer, create a folder named "data". (1 point)
    <br> * Get for the provinces of Peru data for any variable of your concern, the variable has to be measured in several years (you need at least 3 measures if the measures were every 5 or 10 years, or 10 measures if taken yearly). (4 points)
    <br> * Merge that data into the map of provinces of Peru. (3 points)
    <br> * Plot two maps, one with the provinces that improved, and other with the ones that worsen, include the code. (3 points)
    <br> * Publish the two maps. (3 points)
    <br> * Update the README to offer a quick explanation, the data dictionary, and the link to the published map. (2 points)
    <br> * Make sure the code is well organized (explanations, comments, no warnings, no python messages). (2 points)
    
</div>